CREATE TABLE tbCliente(
CPF VARCHAR(12),
NM VARCHAR (100),
ADDRESS1 VARCHAR(50),
ADDRESS2 VARCHAR(50),
NEIGHBORHOOD VARCHAR (50),
CITY VARCHAR (20),
STATE VARCHAR (20),
CEP  VARCHAR (20),
AGE SMALLINT,
SEX VARCHAR(1),
CREDIT_LIMIT FLOAT,
BUY_VOLUM FLOAT,
FISTBUY BIT(1))