#Composite Filters

SELECT * FROM TBproduct;

SELECT * FROM TBproduct WHERE PRICE_LIST BETWEEN 16.007 AND 16.009;
SELECT * FROM TBproduct WHERE PRICE_LIST >= 16.007;
SELECT * FROM TBproduct WHERE PRICE_LIST <= 16.009;
SELECT * FROM TBproduct WHERE PRICE_LIST >= 16.007 AND PRICE_LIST <= 16.009;

SELECT * FROM tbCliente WHERE AGE >= 18 AND AGE <= 22;

SELECT * FROM tbCliente WHERE AGE >= 18 AND AGE <= 22 AND SEX = 'M' ;

SELECT * FROM tbCliente WHERE STATE = 'RJ' OR NEIGHBORHOOD = "Jardins" ;

SELECT * FROM tbCliente WHERE (AGE >= 18 AND AGE <= 22 AND SEX = 'F') OR (CITY = 'Rio de Janeiro ' OR NEIGHBORHOOD = 'Jardins'); 

 